---

command: command[check_disk_uses(ansible)]=/usr/lib/nagios/plugins/check_disk_uses_ansible.sh /dev/sda1 

command_definition: define command {
                            command_name    check_disk_uses(ansible)
                            command_line    $USER1$/check_nrpe -H $HOSTADDRESS$ -c check_disk_uses(ansible)
                            }

command_service: define service {
                         use                             generic-service
                         host_name                       localhost
                         service_description             service check customized by daniel (ansible)
                         check_command                   check_disk_uses(ansible)
                         }

