---

- name: write the plugin shell script
  copy:
    src: ~/nagios_monitoring/roles/create_plugins/tasks/check_disk_uses_ansible.sh
    dest: /usr/lib/nagios/plugins/check_disk_uses_ansible.sh
    owner: root
    group: root
    mode: '0755'

- name: add command to configuration file
  lineinfile:
    insertafter: \\command[daniel_disk]=/usr/lib/nagios/plugins/daniel_disk.sh /dev/sda1\\
    
    line: "{{ command }}"
    path: /etc/nagios/nrpe.cfg
    create: true  

- name: add command definition
  lineinfile: dest=/usr/local/nagios/etc/objects/commands.cfg line= "{{ command_definition }}" 

- name: add command service
  lineinfile: dest=/usr/local/nagios/etc/objects/localhost.cfg line= "{{ command_service }}" 


