---

- name: write the plugin shell scripts
  copy:
    src: ~/nagios_monitoring/roles/create_plugins/tasks/shell_scripts/
    dest: /usr/lib/nagios/plugins/
    owner: root
    group: root
    mode: '0755'

- name: add command to configuration file
  lineinfile:
    path: /etc/nagios/nrpe.cfg
    state: present  
    line: "{{ item }}"
  with_items:
  - "{{ check_disc_uses }}"
  - "{{ check_pid }}"
  - "{{ check_memory }}"
  - "{{ check_status_code }}"
  - "{{ check_volume }}"

- name: add command definition
  lineinfile:
    path: /usr/local/nagios/etc/objects/commands.cfg
    state: present
    line: "{{ item }}"
  with_items:
  - "{{ disc_definition }}"
  - "{{ pid_definition }}"
  - "{{ memory_definition }}"
  - "{{ status_code_definition }}"
  - "{{ volume_definition }}"

- name: add command service
  lineinfile:
    path: /usr/local/nagios/etc/objects/localhost.cfg
    state: present
    line: "{{ item }}"
  with_items:
  - "{{ disc_service }}"       
  - "{{ pid_service }}"       
  - "{{ memory_service }}"       
  - "{{ status_code_service }}"       
  - "{{ volume_service }}"       

